"""Add deleted field to Customer model

Revision ID: 7deefc0f3ece
Revises: 6e48d54afaca
Create Date: 2025-01-22 20:26:47.594380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7deefc0f3ece'
down_revision: Union[str, None] = '6e48d54afaca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('customer', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'deleted_at')
    op.drop_column('customer', 'deleted')
    # ### end Alembic commands ###
