"""edit verificationstatus enum

Revision ID: ce021937723d
Revises: 7deefc0f3ece
Create Date: 2025-01-24 16:09:34.973436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce021937723d'
down_revision: Union[str, None] = '7deefc0f3ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'agent_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('customer', 'verification_status',
               existing_type=mysql.ENUM('none', 'verified', 'pending'),
               type_=sa.Enum('none', 'pending', 'verified', name='verification_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'none'"))
    op.drop_index('customer_email', table_name='customer')
    op.create_index(op.f('ix_customer_customer_email'), 'customer', ['customer_email'], unique=True)
    op.create_index('ix_customer_email', 'customer', ['customer_email'], unique=False)
    op.alter_column('customer_business', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Indicates if the customer is active or not',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('customer_credential', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Indicates if the customer is active or not',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('customer_margin', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Indicates if the customer is active or not',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('customer_payment', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Indicates if the customer is active or not',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_payment', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Indicates if the customer is active or not',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('customer_margin', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Indicates if the customer is active or not',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('customer_credential', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Indicates if the customer is active or not',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('customer_business', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Indicates if the customer is active or not',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index('ix_customer_email', table_name='customer')
    op.drop_index(op.f('ix_customer_customer_email'), table_name='customer')
    op.create_index('customer_email', 'customer', ['customer_email'], unique=True)
    op.alter_column('customer', 'verification_status',
               existing_type=sa.Enum('none', 'pending', 'verified', name='verification_status_enum'),
               type_=mysql.ENUM('none', 'verified', 'pending'),
               existing_nullable=False,
               existing_server_default=sa.text("'none'"))
    op.alter_column('booking', 'agent_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
